### PR TITLE
Remove province

### PR DESCRIPTION
**Pull request by jharris119**
https://github.com/namely/issues/issues/2597

### CODE REVIEW

**Comment by edisgreat** [comment]
+1

**Comment by jharris119** [comment]
@macat @edisgreat is it okay if i hit that "merge pull request" button, or does someone else want to take on that responsibility? :)

**Comment by viola** [comment]
@jharris119 is there a reason why this PR is against master and not develop branch?

**Comment by jharris119** [comment]
@viola Not really, except that it's originally forked off of the master branch on hexorx/countries. (There's `gem 'countries', '~> 0.9.8', git: 'https://github.com/namely/countries.git'` in the namely/namely Gemfile, does that pull from the master branch?)

**Comment by viola** [comment]
@jharris119 NM I see, my bad!

**Pull request merged**
